os:
  osx

before_install:
  - brew update
  - brew install ghc
  - brew install cabal-install
  - brew install agda
  - export PATH=/home/travis/.cabal/bin:${PATH}

script:
  - cabal update
  - make online-atps
  - make install-libraries
  - make problems
  - make reconstruct
  - make check
